'use client';

/**
 * CopyToClipboard — Formats the wishlist as readable text and copies it.
 *
 * Output format:
 * - Wishlist title
 * - Folder/category headings
 * - Item names with optional prices
 * - Total cost
 * - Generated-by footer
 */
import { useState } from 'react';
import { Check, ClipboardCopy } from 'lucide-react';
import { Button } from '@/components/ui/Button';
import { useToast } from '@/components/ui/Toast';

interface ClipboardItem {
  title: string;
  currentPrice: string | null;
  category: string | null;
  starPriority: number;
  purchased: boolean;
}

interface CopyToClipboardProps {
  wishlistTitle: string;
  items: ClipboardItem[];
}

function formatStars(priority: number): string {
  if (priority <= 1) return '';
  return '★'.repeat(priority) + ' ';
}

export function CopyToClipboard({ wishlistTitle, items }: CopyToClipboardProps) {
  const [copied, setCopied] = useState(false);
  const toast = useToast();

  const handleCopy = async () => {
    const unpurchased = items.filter((i) => !i.purchased);

    // Group by category
    const groups = new Map<string, ClipboardItem[]>();
    const uncategorized: ClipboardItem[] = [];

    for (const item of unpurchased) {
      const cat = item.category?.trim();
      if (cat) {
        if (!groups.has(cat)) groups.set(cat, []);
        groups.get(cat)!.push(item);
      } else {
        uncategorized.push(item);
      }
    }

    // Build text
    const lines: string[] = [];
    lines.push(wishlistTitle);
    lines.push('');

    const renderItems = (items: ClipboardItem[]) => {
      for (const item of items) {
        const stars = formatStars(item.starPriority);
        const price = item.currentPrice ? `  $${Number(item.currentPrice).toFixed(2)}` : '';
        lines.push(`• ${stars}${item.title}${price}`);
      }
    };

    // Categorized items
    const categoryNames = [...groups.keys()].sort();
    for (const cat of categoryNames) {
      lines.push(cat);
      renderItems(groups.get(cat)!);
      lines.push('');
    }

    // Uncategorized
    if (uncategorized.length > 0) {
      if (groups.size > 0) lines.push('Other');
      renderItems(uncategorized);
      lines.push('');
    }

    // Total
    const total = unpurchased.reduce((sum, i) => sum + (Number(i.currentPrice) || 0), 0);
    if (total > 0) {
      lines.push(`Estimated Total: $${total.toFixed(2)}`);
      lines.push('');
    }

    lines.push('Generated by DerList');

    const text = lines.join('\n');

    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      toast.success('Wishlist copied to clipboard');
      setTimeout(() => setCopied(false), 2000);
    } catch {
      toast.error('Failed to copy to clipboard');
    }
  };

  return (
    <Button variant="ghost" size="sm" onClick={handleCopy} className="gap-1.5">
      {copied ? (
        <Check className="text-success h-3.5 w-3.5" />
      ) : (
        <ClipboardCopy className="h-3.5 w-3.5" />
      )}
      {copied ? 'Copied' : 'Clipboard'}
    </Button>
  );
}
