/**
 * Integration Catalog — Unified provider registry for all categories.
 *
 * This replaces the separate AI_PROVIDERS / SEARCH_PROVIDERS / PRICE_PROVIDERS
 * arrays with a single catalog that covers all integration categories.
 */

import type { IntegrationCatalogEntry, IntegrationCategory } from './integration-types';

// Re-export original catalog for backward compat
export { AI_PROVIDERS, SEARCH_PROVIDERS, PRICE_PROVIDERS, ALL_PROVIDERS } from './catalog';

// ─── AI Models ───────────────────────────────────────────────────────────────

export const CATALOG_AI: IntegrationCatalogEntry[] = [
  {
    id: 'openai',
    name: 'OpenAI',
    category: 'ai',
    description: 'GPT-4o, o1, and embeddings.',
    website: 'https://platform.openai.com',
    docsUrl: 'https://platform.openai.com/docs',
    pricing: 'paid',
    recommended: true,
    tags: ['gpt', 'chatgpt', 'dall-e', 'whisper'],
    brand: { color: '#10a37f', gradient: 'from-emerald-500/10 to-teal-500/10' },
    capabilities: {
      chat: true,
      streaming: true,
      vision: true,
      functionCalling: true,
      jsonMode: true,
      embeddings: true,
    },
    requiredConfig: [
      {
        key: 'apiKey',
        label: 'API Key',
        type: 'password',
        placeholder: 'sk-...',
        pattern: '^sk-[a-zA-Z0-9_-]{20,}$',
        patternMessage: 'Must start with sk- followed by 20+ characters',
      },
    ],
    optionalConfig: [
      {
        key: 'model',
        label: 'Model',
        type: 'select',
        options: ['gpt-4o', 'gpt-4o-mini', 'o1', 'o1-mini', 'gpt-4-turbo'],
        defaultValue: 'gpt-4o-mini',
        group: 'Model',
      },
      {
        key: 'baseUrl',
        label: 'Base URL',
        type: 'url',
        placeholder: 'https://api.openai.com/v1',
        group: 'Connection',
      },
      {
        key: 'organization',
        label: 'Organization ID',
        type: 'text',
        placeholder: 'org-...',
        group: 'Identity',
      },
      { key: 'project', label: 'Project ID', type: 'text', group: 'Identity' },
      {
        key: 'timeout',
        label: 'Timeout (ms)',
        type: 'number',
        defaultValue: 30000,
        min: 5000,
        max: 120000,
        group: 'Advanced',
      },
    ],
    testConnection: {
      endpoint: '/models',
      method: 'GET',
      successCodes: [200],
      successMetrics: ['modelCount', 'quota'],
    },
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    category: 'ai',
    description: 'Access 300+ models through one API. Free tier available.',
    website: 'https://openrouter.ai',
    docsUrl: 'https://openrouter.ai/docs',
    pricing: 'freemium',
    free: true,
    freeTier: 'Free models (no credits needed)',
    recommended: true,
    supportsHosted: true,
    tags: ['multi-model', 'aggregator', 'free'],
    brand: { color: '#6366f1', gradient: 'from-violet-500/10 to-purple-500/10' },
    capabilities: {
      chat: true,
      streaming: true,
      vision: true,
      functionCalling: true,
      jsonMode: true,
      embeddings: false,
    },
    requiredConfig: [
      {
        key: 'apiKey',
        label: 'API Key',
        type: 'password',
        placeholder: 'sk-or-...',
        pattern: '^sk-or-[a-zA-Z0-9_-]{20,}$',
        patternMessage: 'Must start with sk-or-',
      },
    ],
    optionalConfig: [
      {
        key: 'model',
        label: 'Default Model',
        type: 'text',
        placeholder: 'openrouter/auto',
        group: 'Model',
      },
      {
        key: 'baseUrl',
        label: 'Base URL',
        type: 'url',
        placeholder: 'https://openrouter.ai/api/v1',
        group: 'Connection',
      },
      {
        key: 'httpReferer',
        label: 'HTTP Referer',
        type: 'text',
        placeholder: 'https://your-app.com',
        description: 'For rate limit attribution',
        group: 'Identity',
      },
      {
        key: 'appName',
        label: 'App Name',
        type: 'text',
        placeholder: 'DerList',
        group: 'Identity',
      },
    ],
    testConnection: {
      endpoint: '/models',
      method: 'GET',
      successCodes: [200],
      successMetrics: ['modelCount'],
    },
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    category: 'ai',
    description: 'Claude 4 Sonnet & Opus.',
    website: 'https://anthropic.com',
    docsUrl: 'https://docs.anthropic.com',
    pricing: 'paid',
    recommended: true,
    tags: ['claude', 'sonnet', 'opus', 'safety'],
    brand: { color: '#d4a574', gradient: 'from-amber-500/10 to-orange-500/10' },
    capabilities: {
      chat: true,
      streaming: true,
      vision: true,
      functionCalling: true,
      jsonMode: true,
      embeddings: false,
    },
    requiredConfig: [
      {
        key: 'apiKey',
        label: 'API Key',
        type: 'password',
        placeholder: 'sk-ant-...',
        pattern: '^sk-ant-[a-zA-Z0-9_-]{20,}$',
        patternMessage: 'Must start with sk-ant-',
      },
    ],
    optionalConfig: [
      {
        key: 'model',
        label: 'Model',
        type: 'select',
        options: [
          'claude-sonnet-4-20250514',
          'claude-opus-4-20250514',
          'claude-3-5-haiku-20241022',
        ],
        defaultValue: 'claude-sonnet-4-20250514',
      },
    ],
    testConnection: {
      endpoint: '/v1/messages',
      method: 'POST',
      successCodes: [200, 400],
      successMetrics: ['quota'],
    },
  },
  {
    id: 'google',
    name: 'Google Gemini',
    category: 'ai',
    description: 'Gemini 2.5 Pro/Flash multimodal.',
    website: 'https://ai.google.dev',
    docsUrl: 'https://ai.google.dev/docs',
    pricing: 'freemium',
    free: true,
    freeTier: 'Free tier with rate limits',
    capabilities: {
      chat: true,
      streaming: true,
      vision: true,
      functionCalling: true,
      jsonMode: true,
      embeddings: true,
    },
    requiredConfig: [{ key: 'apiKey', label: 'API Key', type: 'password' }],
    optionalConfig: [
      { key: 'model', label: 'Model', type: 'text', placeholder: 'gemini-2.5-flash' },
    ],
  },
  {
    id: 'groq',
    name: 'Groq',
    category: 'ai',
    description: 'Ultra-fast LPU inference.',
    website: 'https://groq.com',
    docsUrl: 'https://console.groq.com/docs',
    pricing: 'freemium',
    free: true,
    freeTier: 'Generous free tier',
    capabilities: {
      chat: true,
      streaming: true,
      vision: true,
      functionCalling: true,
      jsonMode: true,
      embeddings: false,
    },
    requiredConfig: [{ key: 'apiKey', label: 'API Key', type: 'password', placeholder: 'gsk_...' }],
    optionalConfig: [
      { key: 'model', label: 'Model', type: 'text', placeholder: 'llama-3.3-70b-versatile' },
    ],
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    category: 'ai',
    description: 'DeepSeek V3/R1 code & reasoning.',
    website: 'https://deepseek.com',
    docsUrl: 'https://platform.deepseek.com/docs',
    pricing: 'paid',
    capabilities: {
      chat: true,
      streaming: true,
      vision: false,
      functionCalling: true,
      jsonMode: true,
      embeddings: false,
    },
    requiredConfig: [{ key: 'apiKey', label: 'API Key', type: 'password' }],
    optionalConfig: [
      { key: 'model', label: 'Model', type: 'text', placeholder: 'deepseek-chat' },
      {
        key: 'baseUrl',
        label: 'Base URL',
        type: 'text',
        placeholder: 'https://api.deepseek.com/v1',
      },
    ],
  },
  {
    id: 'mistral',
    name: 'Mistral AI',
    category: 'ai',
    description: 'Mistral Large/Small European AI.',
    website: 'https://mistral.ai',
    docsUrl: 'https://docs.mistral.ai',
    pricing: 'paid',
    capabilities: {
      chat: true,
      streaming: true,
      vision: false,
      functionCalling: true,
      jsonMode: true,
      embeddings: true,
    },
    requiredConfig: [{ key: 'apiKey', label: 'API Key', type: 'password' }],
    optionalConfig: [
      { key: 'model', label: 'Model', type: 'text', placeholder: 'mistral-large-latest' },
    ],
  },
  {
    id: 'cohere',
    name: 'Cohere',
    category: 'ai',
    description: 'Command R+ enterprise RAG.',
    website: 'https://cohere.com',
    docsUrl: 'https://docs.cohere.com',
    pricing: 'freemium',
    capabilities: {
      chat: true,
      streaming: true,
      vision: false,
      functionCalling: true,
      jsonMode: false,
      embeddings: true,
    },
    requiredConfig: [{ key: 'apiKey', label: 'API Key', type: 'password' }],
    optionalConfig: [{ key: 'model', label: 'Model', type: 'text', placeholder: 'command-r-plus' }],
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    category: 'ai',
    description: 'AI with real-time web search.',
    website: 'https://perplexity.ai',
    docsUrl: 'https://docs.perplexity.ai',
    pricing: 'paid',
    capabilities: {
      chat: true,
      streaming: true,
      vision: false,
      functionCalling: false,
      jsonMode: false,
      embeddings: false,
    },
    requiredConfig: [{ key: 'apiKey', label: 'API Key', type: 'password' }],
    optionalConfig: [{ key: 'model', label: 'Model', type: 'text', placeholder: 'sonar-pro' }],
  },
  {
    id: 'xai',
    name: 'xAI (Grok)',
    category: 'ai',
    description: 'Grok-3 real-time reasoning.',
    website: 'https://x.ai',
    docsUrl: 'https://docs.x.ai',
    pricing: 'paid',
    capabilities: {
      chat: true,
      streaming: true,
      vision: true,
      functionCalling: true,
      jsonMode: true,
      embeddings: false,
    },
    requiredConfig: [{ key: 'apiKey', label: 'API Key', type: 'password', placeholder: 'xai-...' }],
    optionalConfig: [{ key: 'model', label: 'Model', type: 'text', placeholder: 'grok-3' }],
  },
  {
    id: 'azure-openai',
    name: 'Azure OpenAI',
    category: 'ai',
    description: 'OpenAI on Azure enterprise.',
    website: 'https://azure.microsoft.com/en-us/products/ai-services/openai-service',
    docsUrl: 'https://learn.microsoft.com/en-us/azure/ai-services/openai/',
    pricing: 'paid',
    capabilities: {
      chat: true,
      streaming: true,
      vision: true,
      functionCalling: true,
      jsonMode: true,
      embeddings: true,
    },
    requiredConfig: [
      { key: 'apiKey', label: 'API Key', type: 'password' },
      {
        key: 'baseUrl',
        label: 'Endpoint',
        type: 'text',
        placeholder: 'https://your-resource.openai.azure.com',
      },
    ],
    optionalConfig: [{ key: 'model', label: 'Deployment', type: 'text', placeholder: 'gpt-4o' }],
  },
  {
    id: 'ollama',
    name: 'Ollama',
    category: 'ai',
    description: 'Run models locally. No API key needed.',
    website: 'https://ollama.ai',
    docsUrl: 'https://github.com/ollama/ollama/blob/main/docs/api.md',
    pricing: 'free',
    free: true,
    freeTier: 'Free (runs locally)',
    selfHosted: true,
    capabilities: {
      chat: true,
      streaming: true,
      vision: true,
      functionCalling: false,
      jsonMode: true,
      embeddings: true,
    },
    requiredConfig: [],
    optionalConfig: [
      { key: 'baseUrl', label: 'Base URL', type: 'text', placeholder: 'http://localhost:11434/v1' },
      { key: 'model', label: 'Model', type: 'text', placeholder: 'llama3.3' },
    ],
  },
  {
    id: 'lmstudio',
    name: 'LM Studio',
    category: 'ai',
    description: 'Local OpenAI-compatible server.',
    website: 'https://lmstudio.ai',
    pricing: 'free',
    free: true,
    freeTier: 'Free (runs locally)',
    selfHosted: true,
    capabilities: {
      chat: true,
      streaming: true,
      vision: false,
      functionCalling: false,
      jsonMode: true,
      embeddings: true,
    },
    requiredConfig: [],
    optionalConfig: [
      { key: 'baseUrl', label: 'Base URL', type: 'text', placeholder: 'http://localhost:1234/v1' },
      { key: 'model', label: 'Model', type: 'text' },
    ],
  },
  {
    id: 'openai-compatible',
    name: 'OpenAI Compatible',
    category: 'ai',
    description: 'Any OpenAI-compatible endpoint.',
    website: '',
    pricing: 'paid',
    capabilities: {
      chat: true,
      streaming: true,
      vision: false,
      functionCalling: false,
      jsonMode: true,
      embeddings: false,
    },
    requiredConfig: [
      { key: 'baseUrl', label: 'Base URL', type: 'text', placeholder: 'https://your-api.com/v1' },
    ],
    optionalConfig: [
      { key: 'apiKey', label: 'API Key', type: 'password' },
      { key: 'model', label: 'Model', type: 'text' },
    ],
  },
  {
    id: 'custom-ai',
    name: 'Custom AI',
    category: 'ai',
    description: 'Connect any AI API with custom configuration.',
    website: '',
    pricing: 'paid',
    requiredConfig: [{ key: 'baseUrl', label: 'Endpoint URL', type: 'text' }],
    optionalConfig: [
      { key: 'apiKey', label: 'API Key', type: 'password' },
      { key: 'model', label: 'Model', type: 'text' },
      { key: 'headers', label: 'Custom Headers (JSON)', type: 'text' },
    ],
  },
];

// ─── Search ──────────────────────────────────────────────────────────────────

export const CATALOG_SEARCH: IntegrationCatalogEntry[] = [
  {
    id: 'brave',
    name: 'Brave Search',
    category: 'search',
    description: 'Web, image, news, and video search with rich results.',
    website: 'https://brave.com/search/api',
    docsUrl: 'https://api.search.brave.com/app/documentation',
    pricing: 'freemium',
    free: true,
    freeTier: '2,000 queries/month free',
    recommended: true,
    supportsHosted: true,
    tags: ['web-search', 'images', 'news', 'privacy'],
    brand: { color: '#fb542b', gradient: 'from-orange-500/10 to-red-500/10' },
    requiredConfig: [{ key: 'apiKey', label: 'API Key', type: 'password', placeholder: 'BSA...' }],
    optionalConfig: [
      {
        key: 'maxResults',
        label: 'Max Results',
        type: 'number',
        placeholder: '8',
        min: 1,
        max: 20,
        defaultValue: 8,
      },
    ],
    endpoints: [
      { type: 'search', supported: true },
      { type: 'images', supported: true },
      { type: 'news', supported: true },
      { type: 'autocomplete', supported: true },
    ],
    testConnection: {
      endpoint: '/res/v1/web/search?q=test&count=1',
      method: 'GET',
      successCodes: [200],
      successMetrics: ['quota'],
    },
  },
  {
    id: 'serpapi',
    name: 'SerpAPI',
    category: 'search',
    description: 'Google, Bing, and YouTube search results API.',
    website: 'https://serpapi.com',
    docsUrl: 'https://serpapi.com/search-api',
    pricing: 'freemium',
    free: true,
    freeTier: '100 searches/month free',
    requiredConfig: [{ key: 'apiKey', label: 'API Key', type: 'password' }],
    endpoints: [
      { type: 'search', supported: true },
      { type: 'images', supported: true },
    ],
  },
  {
    id: 'tavily',
    name: 'Tavily',
    category: 'search',
    description: 'AI-optimized search built for LLM agents.',
    website: 'https://tavily.com',
    docsUrl: 'https://docs.tavily.com',
    pricing: 'freemium',
    free: true,
    freeTier: '1,000 searches/month free',
    recommended: true,
    requiredConfig: [{ key: 'apiKey', label: 'API Key', type: 'password' }],
  },
  {
    id: 'exa',
    name: 'Exa',
    category: 'search',
    description: 'Neural search engine for finding similar content.',
    website: 'https://exa.ai',
    docsUrl: 'https://docs.exa.ai',
    pricing: 'freemium',
    requiredConfig: [{ key: 'apiKey', label: 'API Key', type: 'password' }],
  },
  {
    id: 'firecrawl',
    name: 'Firecrawl',
    category: 'search',
    description: 'Web scraping and crawling API for AI.',
    website: 'https://firecrawl.dev',
    docsUrl: 'https://docs.firecrawl.dev',
    pricing: 'freemium',
    free: true,
    freeTier: '500 pages/month free',
    requiredConfig: [{ key: 'apiKey', label: 'API Key', type: 'password' }],
  },
  {
    id: 'duckduckgo',
    name: 'DuckDuckGo',
    category: 'search',
    description: 'Privacy-focused search. No API key needed.',
    website: 'https://duckduckgo.com',
    pricing: 'free',
    free: true,
    freeTier: 'Free (no API key)',
    requiredConfig: [],
  },
  {
    id: 'google-custom-search',
    name: 'Google Custom Search',
    category: 'search',
    description: 'Google Programmable Search Engine.',
    website: 'https://programmablesearchengine.google.com',
    docsUrl: 'https://developers.google.com/custom-search/v1/overview',
    pricing: 'freemium',
    free: true,
    freeTier: '100 queries/day free',
    requiredConfig: [
      { key: 'apiKey', label: 'API Key', type: 'password' },
      { key: 'cx', label: 'Search Engine ID', type: 'text' },
    ],
  },
  {
    id: 'bing-search',
    name: 'Bing Search',
    category: 'search',
    description: 'Microsoft Bing Web Search API.',
    website: 'https://www.microsoft.com/en-us/bing/apis/bing-web-search-api',
    docsUrl: 'https://learn.microsoft.com/en-us/bing/search-apis/',
    pricing: 'freemium',
    free: true,
    freeTier: '1,000 calls/month free',
    requiredConfig: [{ key: 'apiKey', label: 'API Key', type: 'password' }],
  },
  {
    id: 'kagi',
    name: 'Kagi',
    category: 'search',
    description: 'Premium ad-free search engine.',
    website: 'https://kagi.com',
    docsUrl: 'https://help.kagi.com/kagi/api/',
    pricing: 'paid',
    requiredConfig: [{ key: 'apiKey', label: 'API Key', type: 'password' }],
  },
  {
    id: 'searxng',
    name: 'SearXNG',
    category: 'search',
    description: 'Self-hosted metasearch engine.',
    website: 'https://docs.searxng.org',
    pricing: 'free',
    free: true,
    freeTier: 'Free (self-hosted)',
    selfHosted: true,
    requiredConfig: [
      {
        key: 'baseUrl',
        label: 'Instance URL',
        type: 'text',
        placeholder: 'https://searx.example.com',
      },
    ],
  },
  {
    id: 'custom-search',
    name: 'Custom Search API',
    category: 'search',
    description: 'Connect any search API with a custom endpoint.',
    website: '',
    pricing: 'paid',
    requiredConfig: [{ key: 'baseUrl', label: 'Endpoint URL', type: 'text' }],
    optionalConfig: [
      { key: 'apiKey', label: 'API Key', type: 'password' },
      { key: 'headers', label: 'Custom Headers (JSON)', type: 'text' },
    ],
  },
];

// ─── Shopping ────────────────────────────────────────────────────────────────

export const CATALOG_SHOPPING: IntegrationCatalogEntry[] = [
  {
    id: 'serpapi-shopping',
    name: 'SerpAPI Shopping',
    category: 'shopping',
    description: 'Google Shopping results via SerpAPI.',
    website: 'https://serpapi.com',
    docsUrl: 'https://serpapi.com/google-shopping-api',
    pricing: 'freemium',
    free: true,
    freeTier: '100 searches/month free',
    recommended: true,
    requiredConfig: [{ key: 'apiKey', label: 'API Key', type: 'password' }],
  },
  {
    id: 'rainforest',
    name: 'Rainforest API',
    category: 'shopping',
    description: 'Amazon product data at scale.',
    website: 'https://rainforestapi.com',
    docsUrl: 'https://www.rainforestapi.com/docs',
    pricing: 'paid',
    requiredConfig: [{ key: 'apiKey', label: 'API Key', type: 'password' }],
  },
  {
    id: 'amazon-paapi',
    name: 'Amazon PA-API',
    category: 'shopping',
    description: 'Official Amazon Product Advertising API.',
    website: 'https://affiliate-program.amazon.com',
    docsUrl: 'https://webservices.amazon.com/paapi5/documentation/',
    pricing: 'free',
    free: true,
    freeTier: 'Free with affiliate account',
    requiredConfig: [
      { key: 'accessKey', label: 'Access Key', type: 'password' },
      { key: 'secretKey', label: 'Secret Key', type: 'password' },
      { key: 'partnerTag', label: 'Partner Tag', type: 'text' },
    ],
  },
  {
    id: 'google-shopping',
    name: 'Google Shopping',
    category: 'shopping',
    description: 'Google product search & comparison.',
    website: 'https://shopping.google.com',
    docsUrl: 'https://developers.google.com/shopping-content/reference/rest',
    pricing: 'paid',
    requiredConfig: [{ key: 'apiKey', label: 'API Key', type: 'password' }],
  },
  {
    id: 'custom-shopping',
    name: 'Custom Shopping API',
    category: 'shopping',
    description: 'Connect any shopping/product API.',
    website: '',
    pricing: 'paid',
    requiredConfig: [{ key: 'baseUrl', label: 'Endpoint URL', type: 'text' }],
    optionalConfig: [
      { key: 'apiKey', label: 'API Key', type: 'password' },
      { key: 'headers', label: 'Custom Headers (JSON)', type: 'text' },
    ],
  },
];

// ─── Price Tracking ──────────────────────────────────────────────────────────

export const CATALOG_PRICE: IntegrationCatalogEntry[] = [
  {
    id: 'keepa',
    name: 'Keepa',
    category: 'price',
    description: 'Amazon price history & tracking.',
    website: 'https://keepa.com',
    docsUrl: 'https://keepa.com/#!discuss/t/using-the-keepa-api/47',
    pricing: 'paid',
    recommended: true,
    requiredConfig: [{ key: 'apiKey', label: 'API Key', type: 'password' }],
  },
  {
    id: 'priceapi',
    name: 'PriceAPI',
    category: 'price',
    description: 'Multi-retailer price monitoring.',
    website: 'https://priceapi.com',
    docsUrl: 'https://priceapi.com/documentation',
    pricing: 'paid',
    requiredConfig: [{ key: 'apiKey', label: 'API Key', type: 'password' }],
  },
  {
    id: 'camelcamelcamel',
    name: 'CamelCamelCamel',
    category: 'price',
    description: 'Amazon price alerts & history.',
    website: 'https://camelcamelcamel.com',
    pricing: 'paid',
    comingSoon: true,
    requiredConfig: [{ key: 'apiKey', label: 'API Key', type: 'password' }],
  },
  {
    id: 'rainforest-price',
    name: 'Rainforest',
    category: 'price',
    description: 'Amazon price data via Rainforest API.',
    website: 'https://rainforestapi.com',
    docsUrl: 'https://www.rainforestapi.com/docs',
    pricing: 'paid',
    requiredConfig: [{ key: 'apiKey', label: 'API Key', type: 'password' }],
  },
  {
    id: 'oxylabs',
    name: 'Oxylabs',
    category: 'price',
    description: 'E-commerce scraping & price data.',
    website: 'https://oxylabs.io',
    docsUrl: 'https://developers.oxylabs.io',
    pricing: 'paid',
    requiredConfig: [
      { key: 'username', label: 'Username', type: 'text' },
      { key: 'password', label: 'Password', type: 'password' },
    ],
  },
  {
    id: 'zenrows',
    name: 'ZenRows',
    category: 'price',
    description: 'Web scraping API for price extraction.',
    website: 'https://zenrows.com',
    docsUrl: 'https://docs.zenrows.com',
    pricing: 'freemium',
    free: true,
    freeTier: '1,000 credits free',
    requiredConfig: [{ key: 'apiKey', label: 'API Key', type: 'password' }],
  },
  {
    id: 'scrapingbee',
    name: 'ScrapingBee',
    category: 'price',
    description: 'Web scraping with JS rendering.',
    website: 'https://scrapingbee.com',
    docsUrl: 'https://www.scrapingbee.com/documentation/',
    pricing: 'freemium',
    free: true,
    freeTier: '1,000 credits free',
    requiredConfig: [{ key: 'apiKey', label: 'API Key', type: 'password' }],
  },
  {
    id: 'custom-price',
    name: 'Custom Price API',
    category: 'price',
    description: 'Connect any price tracking API.',
    website: '',
    pricing: 'paid',
    requiredConfig: [{ key: 'baseUrl', label: 'Endpoint URL', type: 'text' }],
    optionalConfig: [
      { key: 'apiKey', label: 'API Key', type: 'password' },
      { key: 'headers', label: 'Custom Headers (JSON)', type: 'text' },
    ],
  },
];

// ─── Media ───────────────────────────────────────────────────────────────────

export const CATALOG_MEDIA: IntegrationCatalogEntry[] = [
  {
    id: 'brave-images',
    name: 'Brave Images',
    category: 'media',
    description: 'Image search via Brave Search API.',
    website: 'https://brave.com/search/api',
    docsUrl: 'https://api.search.brave.com/app/documentation/image-search',
    pricing: 'freemium',
    free: true,
    freeTier: 'Included with Brave Search free tier',
    requiredConfig: [{ key: 'apiKey', label: 'API Key', type: 'password' }],
  },
  {
    id: 'unsplash',
    name: 'Unsplash',
    category: 'media',
    description: 'High-quality free stock photos.',
    website: 'https://unsplash.com',
    docsUrl: 'https://unsplash.com/documentation',
    pricing: 'free',
    free: true,
    freeTier: '50 requests/hour free',
    requiredConfig: [{ key: 'apiKey', label: 'Access Key', type: 'password' }],
  },
  {
    id: 'pexels',
    name: 'Pexels',
    category: 'media',
    description: 'Free stock photos and videos.',
    website: 'https://pexels.com',
    docsUrl: 'https://www.pexels.com/api/documentation/',
    pricing: 'free',
    free: true,
    freeTier: '200 requests/hour free',
    requiredConfig: [{ key: 'apiKey', label: 'API Key', type: 'password' }],
  },
  {
    id: 'pixabay',
    name: 'Pixabay',
    category: 'media',
    description: 'Free images, videos, and music.',
    website: 'https://pixabay.com',
    docsUrl: 'https://pixabay.com/api/docs/',
    pricing: 'free',
    free: true,
    freeTier: 'Free (rate limited)',
    requiredConfig: [{ key: 'apiKey', label: 'API Key', type: 'password' }],
  },
  {
    id: 'tmdb',
    name: 'TMDB',
    category: 'media',
    description: 'Movies & TV show database.',
    website: 'https://themoviedb.org',
    docsUrl: 'https://developer.themoviedb.org/docs',
    pricing: 'free',
    free: true,
    freeTier: 'Free for non-commercial use',
    requiredConfig: [{ key: 'apiKey', label: 'API Key', type: 'password' }],
  },
  {
    id: 'rawg',
    name: 'RAWG',
    category: 'media',
    description: 'Video games database.',
    website: 'https://rawg.io',
    docsUrl: 'https://rawg.io/apidocs',
    pricing: 'free',
    free: true,
    freeTier: 'Free tier available',
    requiredConfig: [{ key: 'apiKey', label: 'API Key', type: 'password' }],
  },
  {
    id: 'youtube',
    name: 'YouTube',
    category: 'media',
    description: 'Video search & metadata.',
    website: 'https://youtube.com',
    docsUrl: 'https://developers.google.com/youtube/v3',
    pricing: 'freemium',
    free: true,
    freeTier: '10,000 units/day free',
    requiredConfig: [{ key: 'apiKey', label: 'API Key', type: 'password' }],
  },
  {
    id: 'spotify',
    name: 'Spotify',
    category: 'media',
    description: 'Music catalog & metadata.',
    website: 'https://developer.spotify.com',
    docsUrl: 'https://developer.spotify.com/documentation/web-api',
    pricing: 'free',
    free: true,
    freeTier: 'Free with developer account',
    requiredConfig: [
      { key: 'clientId', label: 'Client ID', type: 'text' },
      { key: 'clientSecret', label: 'Client Secret', type: 'password' },
    ],
  },
  {
    id: 'custom-media',
    name: 'Custom Media API',
    category: 'media',
    description: 'Connect any media/content API.',
    website: '',
    pricing: 'paid',
    requiredConfig: [{ key: 'baseUrl', label: 'Endpoint URL', type: 'text' }],
    optionalConfig: [
      { key: 'apiKey', label: 'API Key', type: 'password' },
      { key: 'headers', label: 'Custom Headers (JSON)', type: 'text' },
    ],
  },
];

// ─── Automation ──────────────────────────────────────────────────────────────

export const CATALOG_AUTOMATION: IntegrationCatalogEntry[] = [
  {
    id: 'n8n',
    name: 'n8n',
    category: 'automation',
    description: 'Self-hosted workflow automation.',
    website: 'https://n8n.io',
    docsUrl: 'https://docs.n8n.io',
    pricing: 'freemium',
    free: true,
    freeTier: 'Free (self-hosted)',
    selfHosted: true,
    requiredConfig: [
      {
        key: 'baseUrl',
        label: 'Instance URL',
        type: 'text',
        placeholder: 'https://n8n.example.com',
      },
      { key: 'apiKey', label: 'API Key', type: 'password' },
    ],
  },
  {
    id: 'zapier',
    name: 'Zapier',
    category: 'automation',
    description: 'Connect apps and automate workflows.',
    website: 'https://zapier.com',
    docsUrl: 'https://platform.zapier.com/docs',
    pricing: 'freemium',
    free: true,
    freeTier: '100 tasks/month free',
    requiredConfig: [{ key: 'webhookUrl', label: 'Webhook URL', type: 'text' }],
  },
  {
    id: 'make',
    name: 'Make',
    category: 'automation',
    description: 'Visual automation platform (formerly Integromat).',
    website: 'https://make.com',
    docsUrl: 'https://www.make.com/en/api-documentation',
    pricing: 'freemium',
    free: true,
    freeTier: '1,000 operations/month free',
    requiredConfig: [{ key: 'webhookUrl', label: 'Webhook URL', type: 'text' }],
  },
  {
    id: 'ifttt',
    name: 'IFTTT',
    category: 'automation',
    description: 'Simple if-this-then-that automations.',
    website: 'https://ifttt.com',
    docsUrl: 'https://ifttt.com/docs',
    pricing: 'freemium',
    free: true,
    freeTier: '2 applets free',
    requiredConfig: [{ key: 'webhookKey', label: 'Webhook Key', type: 'password' }],
  },
  {
    id: 'webhook',
    name: 'Webhook',
    category: 'automation',
    description: 'Send events to any webhook URL.',
    website: '',
    pricing: 'free',
    free: true,
    freeTier: 'Free',
    requiredConfig: [{ key: 'webhookUrl', label: 'Webhook URL', type: 'text' }],
    optionalConfig: [
      { key: 'headers', label: 'Custom Headers (JSON)', type: 'text' },
      { key: 'secret', label: 'Signing Secret', type: 'password' },
    ],
  },
  {
    id: 'rest-api',
    name: 'REST API',
    category: 'automation',
    description: 'Call any REST API endpoint.',
    website: '',
    pricing: 'paid',
    requiredConfig: [{ key: 'baseUrl', label: 'Base URL', type: 'text' }],
    optionalConfig: [
      { key: 'apiKey', label: 'API Key', type: 'password' },
      { key: 'headers', label: 'Custom Headers (JSON)', type: 'text' },
    ],
  },
  {
    id: 'custom-automation',
    name: 'Custom Automation',
    category: 'automation',
    description: 'Build a custom automation integration.',
    website: '',
    pricing: 'paid',
    requiredConfig: [{ key: 'baseUrl', label: 'Endpoint URL', type: 'text' }],
    optionalConfig: [
      { key: 'apiKey', label: 'API Key', type: 'password' },
      { key: 'headers', label: 'Custom Headers (JSON)', type: 'text' },
    ],
  },
];

// ─── Unified Catalog ─────────────────────────────────────────────────────────

export const INTEGRATION_CATALOG: IntegrationCatalogEntry[] = [
  ...CATALOG_AI,
  ...CATALOG_SEARCH,
  ...CATALOG_SHOPPING,
  ...CATALOG_PRICE,
  ...CATALOG_MEDIA,
  ...CATALOG_AUTOMATION,
];

/** Get integration entry by ID. */
export function getIntegrationEntry(id: string): IntegrationCatalogEntry | undefined {
  return INTEGRATION_CATALOG.find((p) => p.id === id);
}

/** Get all integrations for a category. */
export function getIntegrationsByCategory(
  category: IntegrationCategory
): IntegrationCatalogEntry[] {
  return INTEGRATION_CATALOG.filter((p) => p.category === category);
}

/** Search integrations by name, description, tags, capabilities, or category. */
export function searchIntegrations(query: string): IntegrationCatalogEntry[] {
  const q = query.toLowerCase().trim();
  if (!q) return INTEGRATION_CATALOG;
  return INTEGRATION_CATALOG.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.description.toLowerCase().includes(q) ||
      p.category.includes(q) ||
      p.tags?.some((tag) => tag.toLowerCase().includes(q)) ||
      (Array.isArray(p.capabilities) && p.capabilities.some((cap) => cap.toLowerCase().includes(q)))
  );
}

/** Summary counts by category. */
export const INTEGRATION_COUNTS = {
  ai: CATALOG_AI.length,
  search: CATALOG_SEARCH.length,
  shopping: CATALOG_SHOPPING.length,
  price: CATALOG_PRICE.length,
  media: CATALOG_MEDIA.length,
  automation: CATALOG_AUTOMATION.length,
  total: INTEGRATION_CATALOG.length,
};
